### ISSUE TITLE
Error cannot find module

### ISSUE THREAD

**Issue by mehimanshupatil** [jlarmstrongiv/tfjs-node-lambda#7]
I am trying to use this library but whenever I hit lambda function following error is returned
```
2022-04-20T08:45:37.528Z	d3c10b8f-1436-43b7-96bd-31dce5e13125	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "Cannot find module '@tensorflow/tfjs-converter'\nRequire stack:\n- /tmp/tfjs-node/node_modules/@tensorflow/tfjs/dist/tf.node.js\n- /tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/kernels/_FusedMatMul.js\n- /tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/register_all_kernels.js\n- /tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/index.js\n- /tmp/tfjs-node/index.js\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/tmp/tfjs-node/node_modules/@tensorflow/tfjs/dist/tf.node.js",
        "/tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/kernels/_FusedMatMul.js",
        "/tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/register_all_kernels.js",
        "/tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/index.js",
        "/tmp/tfjs-node/index.js",
        "/var/task/app.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module '@tensorflow/tfjs-converter'",
        "Require stack:",
        "- /tmp/tfjs-node/node_modules/@tensorflow/tfjs/dist/tf.node.js",
        "- /tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/kernels/_FusedMatMul.js",
        "- /tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/register_all_kernels.js",
        "- /tmp/tfjs-node/node_modules/@tensorflow/tfjs-node/dist/index.js",
        "- /tmp/tfjs-node/index.js",
        "- /var/task/app.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:101:18)",
        "    at Object.<anonymous> (/tmp/tfjs-node/node_modules/@tensorflow/tfjs/dist/tf.node.js:23:21)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)"
    ]
}

```

**Comment by jlarmstrongiv** [comment]
@mehimanshupatil do you have a GitHub repo where the bug can be reproduced?

**Comment by mehimanshupatil** [comment]
ok, I don't have repo but let me share info about it.

version used  [2.0.22](https://github.com/jlarmstrongiv/tfjs-node-lambda/compare/v2.0.21...v2.0.22)
nodejs version [nodejs14.x-tf3.16.0.br](https://github.com/jlarmstrongiv/tfjs-node-lambda/releases/download/v2.0.22/nodejs14.x-tf3.16.0.br)

what I think is while fixing #6 the @tensorflow/tfjs-converter from node_modules is removed before archiving but is required in @tensorflow/tfjs/dist/tf.node.js. 

so I tried an older version ie 2.0.11 [nodejs14.x-tf2.8.6.br](https://github.com/jlarmstrongiv/tfjs-node-lambda/releases/download/v2.0.11/nodejs14.x-tf2.8.6.br) and it works

**Comment by jlarmstrongiv** [comment]
> I don't have repo

@mehimanshupatil again, I need a repo to get a reproducible error.

The models I have used don’t require  https://www.npmjs.com/package/@tensorflow/tfjs-converter and the tensorflowjs_wizard utility should really be used beforehand.

**Comment by mehimanshupatil** [comment]
https://github.com/mehimanshupatil/saliency check this

**Comment by jlarmstrongiv** [comment]
While I dig into this, I think I have a quick workaround for you—could you try installing https://www.npmjs.com/package/@tensorflow/tfjs-converter in your package dependencies manually?

**Comment by mehimanshupatil** [comment]
I tried but this workaround doesn't work
as the uncompressed folder is in /tmp/tfjs-node/node_module and `/tmp/tfjs-node/node_modules/@tensorflow/tfjs/dist/tf.node.js` js will look in the same node_module

**Comment by julesGoullee** [comment]
Hi @jlarmstrongiv I'm down with the same issue. If you try the branch dev https://github.com/abricot-studio/avant-garde/tree/dev/packages/server with node 12 no prob.
When I try to upgrade to node 14 https://github.com/abricot-studio/avant-garde/tree/update-node/packages/server, I'm facing the same issue.
I've also try (without success to manually install @tensorflow/tfjs-converter, also to copy it under the tmp node_module of tfjs node_module) doesn't change anything.

**Comment by jlarmstrongiv** [comment]
@julesGoullee updated tfjs-node-lambda to include tfjs-backend-webgl and tfjs-converter 👍 please note that you may need to increase your tmp size https://aws.amazon.com/blogs/aws/aws-lambda-now-supports-up-to-10-gb-ephemeral-storage/ (it may take an hour for a new build 3.0.x to be published)
