### ISSUE TITLE
Question about deployment in Vercel and if it can be implemented with UpscalerJS

### ISSUE THREAD

**Issue by Abel1011** [jlarmstrongiv/tfjs-node-lambda#8]
Hello, good morning. Thanks for the work on the library. I am in research phase if I can apply UpscalerJS in my Next.js application deployed in Vercel. In this regard, will you have any example of using this library in Next.js? I would also like to consult you if it is possible to use UpscalerJS in my API routes with this library. Thank you very much in advance for the support you can give me.

**Comment by jlarmstrongiv** [comment]
Hi @Abel1011 , 

I accidentally missed your email issue notification.

I would recommend using serverless for upscalerjs.  Serverless supports container images, longer timeouts, and larger memory.  They give more flexibility and options than vercel for deployment, which you will need for UpscalerJS to work inside aws lambda.  

Normal vercel functions are based on the same aws lambda runtime, while there edge functions are based on cloudflare workers.  Configuring your own aws lambda with serverless is the easiest way for you to achieve your goals.
