### ISSUE TITLE
Even with this library the Lambda limit is exceeded

### ISSUE THREAD

**Issue by ismaelheinen** [jlarmstrongiv/tfjs-node-lambda#9]
Calling packages:

```
const loadTf = require("tfjs-node-lambda");
const { default: axios } = require("axios");

import writeFile from "./fileswriteFile";
import { Readable } from "stream";
```

---

And running at the beginning of the function:

```
  const response = await axios.get(
    "https://github.com/jlarmstrongiv/tfjs-node-lambda/releases/download/v2.0.10/nodejs12.x-tf2.8.6.br",
    { responseType: "arraybuffer" }
  );

  const readStream = Readable.from(response.data);
  let tf = await loadTf(readStream);
```
  
  ---
  
  I'm managing to use tf locally this way, but when deploying, the same problem as the original package occurs, the size limit is exceeded, the tfjs-node-lambda folder on node_modules is about 300mb.
  
  Some additional configuration is needed, perhaps in the serverless framework?

**Comment by jlarmstrongiv** [comment]
Hi @ismaelheinen, 

That additional size is from https://github.com/jlarmstrongiv/tfjs-node-lambda/issues/7

Including `@tensorflow/tfjs-converter` and `tfjs-backend-webgl` caused other models to crash, so I had to add it back in.  

If you use the serverless framework, consider using a larger ephemeral storage ( /tmp ) between 512 MB and 10,240 MB or container images.

**Comment by jlarmstrongiv** [comment]
@ismaelheinen actually, revising my previous comment

It should still work, please check and see why tfjs-node-lambda is so large.  Can you attach a zip file example?

This library only has these files, from the package.json settings:

```
"files": [
    "package.json",
    "index.js",
    "matrix.json"
  ],
```

The library works by downloading your specific tensorflow releases to the `/tmp` space, to avoid the `node_modules` size limit.

Can you ensure that no other large packages like the original tensorflow packages are being included with your bundle?
